---
# tasks file for 1c_ls

#- name: Install required packages
- include: "install-{{ ansible_os_family }}.yml"

- name: Copy userparameter for license server
  copy:
    src: userparameter_1c-ls.conf
    dest: /etc/zabbix/zabbix_agentd.d/
    owner: root
    group: root
    mode: 0644
  notify:
    - Add host to group for restart zabbix agent

- name: Copy main script for license server
  copy:
    src: 1c_license_server.sh
    dest: /var/lib/zabbix/scripts/
    owner: zabbix
    group: zabbix
    mode: 0755

- name: Make cron job for license info
  copy:
    src: 1c_ls_license_info.sh
    dest: /etc/cron.hourly/1c_ls_license_info
    owner: root
    group: root
    mode: 0755
