---
# tasks file for 1c_ws
- name: Copy userparameter for work server
  copy:
    src: userparameter_1c-ws.conf
    dest: /etc/zabbix/zabbix_agentd.d/
    owner: root
    group: root
    mode: 0644

- name: Copy main script for work server
  copy:
    src: 1c_work_server.sh
    dest: /etc/zabbix/scripts/
    owner: zabbix
    group: zabbix
    mode: 0755
