---
# tasks file for 1c_ws

#- name: Install required packages
- include: "install-{{ ansible_os_family }}.yml"

- name: Copy userparameter for work server
  copy:
    src: userparameter_1c-ws.conf
    dest: /etc/zabbix/zabbix_agentd.d/
    owner: root
    group: root
    mode: 0644
  notify:
    - Add host to group for restart zabbix agent

- name: Copy main script for work server
  copy:
    src: 1c_work_server.sh
    dest: /etc/zabbix/scripts/
    owner: root
    group: root
    mode: 0755

- name: Make directory for 1C tech log
  file:
    name: /var/log/1C
    owner: usr1cv8
    group: grp1cv8
    state: directory
    mode: 0750

- name: Make directory for 1C tech log
  file:
    name: /var/log/1C/zabbix
    owner: usr1cv8
    group: grp1cv8
    state: directory
    mode: 0750

- name: Make directory for problem log
  file:
    name: /var/log/1C/zabbix/problem_log
    owner: zabbix
    group: grp1cv8
    state: directory
    mode: 0750

- name: Attach zabbix user to 1C group
  user:
    name: zabbix
    groups: grp1cv8
    append: yes

