---
# tasks file for general
- name: Make directory for template scripts
  file:
    path: /var/lib/zabbix/scripts
    state: directory
    owner: zabbix
    group: zabbix
    mode: 0755

- name: Copy common module script
  copy:
    src: 1c_common_module.sh
    dest: /var/lib/zabbix/scripts/
    owner: zabbix
    group: zabbix
    mode: 0755
