---

- hosts: srv1c
  gather_facts: no
  become: yes
  roles:
    - general

- hosts: srv1c_ws
  become: yes
  roles:
    - srv1c_ws

- hosts: srv1c_ls
  become: yes
  roles:
    - srv1c_ls

- hosts: srv1c_cs
  gather_facts: no
  become: yes
  roles:
    - srv1c_cs

- hosts: hosts_to_restart
  gather_facts: no
  become: yes
  tasks:
    - name: Restart zabbix agent
      service:
        name: zabbix-agent
        state: restarted
